[package]
name = "trim"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.7"
walkdir = "2.4.0"
rayon = "1.8.0"